cask_args appdir: '/Applications'

tap "homebrew/bundle"
tap "homebrew/services"
tap "kong/deck"
tap "hashicorp/tap"
tap "joemiller/taps"

cask 'discord'
cask 'dropbox'
cask 'spotify'
cask 'dbeaver-community'
cask 'postman'
cask 'visual-studio-code'
cask 'vlc'
cask 'appcleaner'
cask 'raycast'
cask 'flux'
cask 'iterm2'
cask 'keepassxc'
cask 'slack'
cask 'shadow'
cask 'scroll-reverser'

brew 'asdf'
brew 'tig'
brew 'pipx'
brew 'awscli'
brew 'coreutils'
brew 'colima'
brew 'chezmoi'
brew 'docker'
brew 'docker-compose'
brew 'docker-buildx'
brew 'fzf'
brew "git"
brew "git-grab"
brew "git-lfs"
brew "zsh"
brew "vim"
brew "jq"
brew "gpg"
brew "tree"
brew "colordiff"
brew "wget"
brew "tfenv"
brew "tgenv"
brew "kind"
brew "kube-ps1"
brew "kubectl"
brew "krew"
brew "kubectx"
brew "helm"
brew "k9s"
brew "vault"
brew "joemiller/taps/vault-token-helper"
brew "vale"
brew "kong/deck/deck"
brew "cloudflared"
brew "pnpm"
brew "nvm"
brew "fluxcd/tap/flux"
brew "postgresql"
